services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://host.docker.internal:5432/keycloak_db
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_password
      - KC_DB_SCHEMA=public
      - KC_DB_MIGRATION_STRATEGY=update
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_LEVEL=DEBUG
    ports:
      - "8080:8080"
    command: start-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge